version: "3.8"
services:    
  app:
    build:
      context: ./app
    restart: always

    
  nginx:
    image: nginx:1.25.2-bookworm
    ports:
      - "8089:8089"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
    restart: "no"
    depends_on:
      - app
